<script setup lang="ts">
  export function th14SpellCard(spellCardId: number){
    const spellCardMap=[
      {id: 1, ja: "氷符「アルティメットブリザード」", en: 'Ice Sign "Ultimate Blizzard"'},
      {id: 2, ja: "氷符「アルティメットブリザード」", en: 'Ice Sign "Ultimate Blizzard"'},
      {id: 3, ja: "水符「テイルフィンスラップ」", en: 'Water Sign "Tail Fin Slap"'},
      {id: 4, ja: "水符「テイルフィンスラップ」", en: 'Water Sign "Tail Fin Slap"'},
      {id: 5, ja: "水符「テイルフィンスラップ」", en: 'Water Sign "Tail Fin Slap"'},
      {id: 6, ja: "水符「テイルフィンスラップ」", en: 'Water Sign "Tail Fin Slap"'},
      {id: 7, ja: "鱗符「スケールウェイブ」", en: 'Scale Sign "Scale Wave"'},
      {id: 8, ja: "鱗符「スケールウェイブ」", en: 'Scale Sign "Scale Wave"'},
      {id: 9, ja: "鱗符「逆鱗の荒波」", en: 'Scale Sign "Raging Waves of the Reversed Scale"'},
      {id: 10, ja: "鱗符「逆鱗の大荒波」", en: 'Scale Sign "Great Raging Waves of the Reversed Scale"'},
      {id: 11, ja: "飛符「フライングヘッド」", en: 'Flight Sign "Flying Head"'},
      {id: 12, ja: "飛符「フライングヘッド」", en: 'Flight Sign "Flying Head"'},
      {id: 13, ja: "飛符「フライングヘッド」", en: 'Flight Sign "Flying Head"'},
      {id: 14, ja: "飛符「フライングヘッド」", en: 'Flight Sign "Flying Head"'},
      {id: 15, ja: "首符「クローズアイショット」", en: 'Neck Sign "Close-Eye Shot"'},
      {id: 16, ja: "首符「クローズアイショット」", en: 'Neck Sign "Close-Eye Shot"'},
      {id: 17, ja: "首符「ろくろ首飛来」", en: 'Neck Sign "Rokurokubi Flight"'},
      {id: 18, ja: "首符「ろくろ首飛来」", en: 'Neck Sign "Rokurokubi Flight"'},
      {id: 19, ja: "飛頭「マルチプリケイティブヘッド」", en: 'Flying Head "Multiplicative Head"'},
      {id: 20, ja: "飛頭「マルチプリケイティブヘッド」", en: 'Flying Head "Multiplicative Head"'},
      {id: 21, ja: "飛頭「セブンズヘッド」", en: 'Flying Head "Seventh Head"'},
      {id: 22, ja: "飛頭「ナインズヘッド」", en: 'Flying Head "Ninth Head"'},
      {id: 23, ja: "飛頭「デュラハンナイト」", en: 'Flying Head "Dullahan Night"'},
      {id: 24, ja: "飛頭「デュラハンナイト」", en: 'Flying Head "Dullahan Night"'},
      {id: 25, ja: "飛頭「デュラハンナイト」", en: 'Flying Head "Dullahan Night"'},
      {id: 26, ja: "飛頭「デュラハンナイト」", en: 'Flying Head "Dullahan Night"'},
      {id: 27, ja: "牙符「月下の犬歯」", en: 'Fang Sign "Moonlit Canine Teeth"'},
      {id: 28, ja: "牙符「月下の犬歯」", en: 'Fang Sign "Moonlit Canine Teeth"'},
      {id: 29, ja: "変身「トライアングルファング」", en: 'Transformation "Triangle Fang"'},
      {id: 30, ja: "変身「トライアングルファング」", en: 'Transformation "Triangle Fang"'},
      {id: 31, ja: "変身「スターファング」", en: 'Transformation "Star Fang"'},
      {id: 32, ja: "変身「スターファング」", en: 'Transformation "Star Fang"'},
      {id: 33, ja: "咆哮「ストレンジロア」", en: 'Roar "Strange Roar"'},
      {id: 34, ja: "咆哮「ストレンジロア」", en: 'Roar "Strange Roar"'},
      {id: 35, ja: "咆哮「満月の遠吠え」", en: 'Roar "Full Moon Howling"'},
      {id: 36, ja: "咆哮「満月の遠吠え」", en: 'Roar "Full Moon Howling"'},
      {id: 37, ja: "狼符「スターリングパウンス」", en: 'Wolf Sign "Star Ring Pounce"'},
      {id: 38, ja: "狼符「スターリングパウンス」", en: 'Wolf Sign "Star Ring Pounce"'},
      {id: 39, ja: "天狼「ハイスピードパウンス」", en: 'Sirius "High-Speed Pounce"'},
      {id: 40, ja: "天狼「ハイスピードパウンス」", en: 'Sirius "High-Speed Pounce"'},
      {id: 41, ja: "平曲「祇園精舎の鐘の音」", en: 'Heikyoku "Sounds of Jetavana\'s Bell"'},
      {id: 42, ja: "平曲「祇園精舎の鐘の音」", en: 'Heikyoku "Sounds of Jetavana\'s Bell"'},
      {id: 43, ja: "平曲「祇園精舎の鐘の音」", en: 'Heikyoku "Sounds of Jetavana\'s Bell"'},
      {id: 44, ja: "平曲「祇園精舎の鐘の音」", en: 'Heikyoku "Sounds of Jetavana\'s Bell"'},
      {id: 45, ja: "怨霊「耳無し芳一」", en: 'Vengeful Spirit "Hoichi the Earless"'},
      {id: 46, ja: "怨霊「耳無し芳一」", en: 'Vengeful Spirit "Hoichi the Earless"'},
      {id: 47, ja: "怨霊「平家の大怨霊」", en: 'Vengeful Spirit "Great Vengeful Spirit of Taira"'},
      {id: 48, ja: "怨霊「平家の大怨霊」", en: 'Vengeful Spirit "Great Vengeful Spirit of Taira"'},
      {id: 49, ja: "楽符「邪悪な五線譜」", en: 'Music Sign "Wicked Musical Score"'},
      {id: 50, ja: "楽符「邪悪な五線譜」", en: 'Music Sign "Wicked Musical Score"'},
      {id: 51, ja: "楽符「凶悪な五線譜」", en: 'Music Sign "Malicious Musical Score"'},
      {id: 52, ja: "楽符「ダブルスコア」", en: 'Music Sign "Double Score"'},
      {id: 53, ja: "琴符「諸行無常の琴の音」", en: 'Koto Sign "Sounds of Anicca\'s Koto"'},
      {id: 54, ja: "琴符「諸行無常の琴の音」", en: 'Koto Sign "Sounds of Anicca\'s Koto"'},
      {id: 55, ja: "琴符「諸行無常の琴の音」", en: 'Koto Sign "Sounds of Anicca\'s Koto"'},
      {id: 56, ja: "琴符「諸行無常の琴の音」", en: 'Koto Sign "Sounds of Anicca\'s Koto"'},
      {id: 57, ja: "響符「平安の残響」", en: 'Echo Sign "Heian\'s Reverberation"'},
      {id: 58, ja: "響符「平安の残響」", en: 'Echo Sign "Heian\'s Reverberation"'},
      {id: 59, ja: "響符「エコーチェンバー」", en: 'Echo Sign "Echo Chamber"'},
      {id: 60, ja: "響符「エコーチェンバー」", en: 'Echo Sign "Echo Chamber"'},
      {id: 61, ja: "箏曲「下克上送箏曲」", en: 'Koto Music "Social Upheaval Koto Music Complement"'},
      {id: 62, ja: "箏曲「下克上送箏曲」", en: 'Koto Music "Social Upheaval Koto Music Complement"'},
      {id: 63, ja: "箏曲「下克上レクイエム」", en: 'Koto Music "Social Upheaval Requiem"'},
      {id: 64, ja: "箏曲「下克上レクイエム」", en: 'Koto Music "Social Upheaval Requiem"'},
      {id: 65, ja: "欺符「逆針撃」", en: 'Deceit Sign "Reverse Needle Attack"'},
      {id: 66, ja: "欺符「逆針撃」", en: 'Deceit Sign "Reverse Needle Attack"'},
      {id: 67, ja: "欺符「逆針撃」", en: 'Deceit Sign "Reverse Needle Attack"'},
      {id: 68, ja: "欺符「逆針撃」", en: 'Deceit Sign "Reverse Needle Attack"'},
      {id: 69, ja: "逆符「鏡の国の弾幕」", en: 'Reverse Sign "Danmaku Through the Looking-Glass"'},
      {id: 70, ja: "逆符「鏡の国の弾幕」", en: 'Reverse Sign "Danmaku Through the Looking-Glass"'},
      {id: 71, ja: "逆符「イビルインザミラー」", en: 'Reverse Sign "Evil in the Mirror"'},
      {id: 72, ja: "逆符「イビルインザミラー」", en: 'Reverse Sign "Evil in the Mirror"'},
      {id: 73, ja: "逆符「天地有用」", en: 'Reverse Sign "This Side Down"'},
      {id: 74, ja: "逆符「天地有用」", en: 'Reverse Sign "This Side Down"'},
      {id: 75, ja: "逆符「天下転覆」", en: 'Reverse Sign "Overturning All Under Heaven"'},
      {id: 76, ja: "逆符「天下転覆」", en: 'Reverse Sign "Overturning All Under Heaven"'},
      {id: 77, ja: "逆弓「天壌夢弓」", en: 'Reverse Bow "Dream Bow of Heaven & Earth"'},
      {id: 78, ja: "逆弓「天壌夢弓」", en: 'Reverse Bow "Dream Bow of Heaven & Earth"'},
      {id: 79, ja: "逆弓「天壌夢弓の詔勅」", en: 'Reverse Bow "Decree of the Dream Bow of Heaven & Earth"'},
      {id: 80, ja: "逆弓「天壌夢弓の詔勅」", en: 'Reverse Bow "Decree of the Dream Bow of Heaven & Earth"'},
      {id: 81, ja: "逆転「リバースヒエラルキー」", en: 'Turnabout "Reverse Hierarchy"'},
      {id: 82, ja: "逆転「リバースヒエラルキー」", en: 'Turnabout "Reverse Hierarchy"'},
      {id: 83, ja: "逆転「チェンジエアブレイブ」", en: 'Turnabout "Change Air Brave"'},
      {id: 84, ja: "逆転「チェンジエアブレイブ」", en: 'Turnabout "Change Air Brave"'},
      {id: 85, ja: "小弾「小人の道」", en: 'Small Barrage "Inchling\'s Path"'},
      {id: 86, ja: "小弾「小人の道」", en: 'Small Barrage "Inchling\'s Path"'},
      {id: 87, ja: "小弾「小人の茨道」", en: 'Small Barrage "Inchling\'s Thorny Path"'},
      {id: 88, ja: "小弾「小人の茨道」", en: 'Small Barrage "Inchling\'s Thorny Path"'},
      {id: 89, ja: "小槌「大きくなあれ」", en: 'Mallet "Grow Bigger!"'},
      {id: 90, ja: "小槌「大きくなあれ」", en: 'Mallet "Grow Bigger!"'},
      {id: 91, ja: "小槌「もっと大きくなあれ」", en: 'Mallet "Grow Even Bigger!"'},
      {id: 92, ja: "小槌「もっと大きくなあれ」", en: 'Mallet "Grow Even Bigger!"'},
      {id: 93, ja: "妖剣「輝針剣」", en: 'Bewitched Sword "Shining Needle Sword"'},
      {id: 94, ja: "妖剣「輝針剣」", en: 'Bewitched Sword "Shining Needle Sword"'},
      {id: 95, ja: "妖剣「輝針剣」", en: 'Bewitched Sword "Shining Needle Sword"'},
      {id: 96, ja: "妖剣「輝針剣」", en: 'Bewitched Sword "Shining Needle Sword"'},
      {id: 97, ja: "小槌「お前が大きくなあれ」", en: 'Mallet "You Grow Bigger!"'},
      {id: 98, ja: "小槌「お前が大きくなあれ」", en: 'Mallet "You Grow Bigger!"'},
      {id: 99, ja: "小槌「お前が大きくなあれ」", en: 'Mallet "You Grow Bigger!"'},
      {id: 100, ja: "小槌「お前が大きくなあれ」", en: 'Mallet "You Grow Bigger!"'},
      {id: 101, ja: "「進撃の小人」", en: '"Attack on Dwarf"'},
      {id: 102, ja: "「進撃の小人」", en: '"Attack on Dwarf"'},
      {id: 103, ja: "「ウォールオブイッスン」", en: '"Wall of Issun"'},
      {id: 104, ja: "「ウォールオブイッスン」", en: '"Wall of Issun"'},
      {id: 105, ja: "「ホップオマイサムセブン」", en: '"Hop-o\'-My-Thumb Seven"'},
      {id: 106, ja: "「ホップオマイサムセブン」", en: '"Hop-o\'-My-Thumb Seven"'},
      {id: 107, ja: "「七人の一寸法師」", en: '"The Seven Issun-Boshi"'},
      {id: 108, ja: "「七人の一寸法師」", en: '"The Seven Issun-Boshi"'},
      {id: 109, ja: "弦楽「嵐のアンサンブル」", en: 'String Music "Storm Ensemble"'},
      {id: 110, ja: "弦楽「浄瑠璃世界」", en: 'String Music "Joururi World"'},
      {id: 111, ja: "一鼓「暴れ宮太鼓」", en: 'First Drum "Raging Temple Taiko"'},
      {id: 112, ja: "二鼓「怨霊アヤノツヅミ」", en: 'Second Drum "Vengeful Spirit Aya-no-Tsuzumi"'},
      {id: 113, ja: "三鼓「午前零時のスリーストライク」", en: 'Third Drum "Three Strikes at Midnight"'},
      {id: 114, ja: "死鼓「ランドパーカス」", en: 'Death Drum "Land Percuss"'},
      {id: 115, ja: "五鼓「デンデン太鼓」", en: 'Fifth Drum "Den-Den Daiko"'},
      {id: 116, ja: "六鼓「オルタネイトスティッキング」", en: 'Sixth Drum "Alternate Sticking"'},
      {id: 117, ja: "七鼓「高速和太鼓ロケット」", en: 'Seventh Drum "High Speed Taiko Rocket"'},
      {id: 118, ja: "八鼓「雷神の怒り」", en: 'Eighth Drum "Thunder God\'s Anger"'},
      {id: 119, ja: "「ブルーレディショー」", en: '"Blue Lady Show"'},
      {id: 120, ja: "「プリスティンビート」", en: '"Pristine Beat"'},
    ]
  }
</script>