<script setup lang="ts">
  export function th16SpellCard(spellCardId: number){
    const spellCardMap=[
      {id: 1, ja: "蝶符「ミニットスケールス」", en: 'Butterfly Sign "Minute Scales"'},
      {id: 2, ja: "蝶符「ミニットスケールス」", en: 'Butterfly Sign "Minute Scales"'},
      {id: 3, ja: "蝶符「アゲハの鱗粉」", en: 'Butterfly Sign "Swallowtail\'s Scales"'},
      {id: 4, ja: "蝶符「アゲハの鱗粉」", en: 'Butterfly Sign "Swallowtail\'s Scales"'},
      {id: 5, ja: "蝶符「フラッタリングサマー」", en: 'Butterfly Sign "Fluttering Summer"'},
      {id: 6, ja: "蝶符「フラッタリングサマー」", en: 'Butterfly Sign "Fluttering Summer"'},
      {id: 7, ja: "蝶符「真夏の羽ばたき」", en: 'Butterfly Sign "Midsummer Wingbeats"'},
      {id: 8, ja: "蝶符「真夏の羽ばたき」", en: 'Butterfly Sign "Midsummer Wingbeats"'},
      {id: 9, ja: "雨符「囚われの秋雨」", en: 'Rain Sign "Imprisoning Autumn Rain"'},
      {id: 10, ja: "雨符「囚われの秋雨」", en: 'Rain Sign "Imprisoning Autumn Rain"'},
      {id: 11, ja: "雨符「呪われた柴榑雨」", en: 'Rain Sign "Cursed Torrential Rain"'},
      {id: 12, ja: "雨符「呪われた柴榑雨」", en: 'Rain Sign "Cursed Torrential Rain"'},
      {id: 13, ja: "刃符「山姥の包丁研ぎ」", en: 'Blade Sign "Yamanba\'s Kitchen Knife Sharpening"'},
      {id: 14, ja: "刃符「山姥の包丁研ぎ」", en: 'Blade Sign "Yamanba\'s Kitchen Knife Sharpening"'},
      {id: 15, ja: "刃符「山姥の鬼包丁研ぎ」", en: 'Blade Sign "Yamanba\'s Oni Kitchen Knife Sharpening"'},
      {id: 16, ja: "刃符「山姥の鬼包丁研ぎ」", en: 'Blade Sign "Yamanba\'s Oni Kitchen Knife Sharpening"'},
      {id: 17, ja: "尽符「マウンテンマーダー」", en: 'Blade Exhaustion Sign "Mountain Murder"'},
      {id: 18, ja: "尽符「マウンテンマーダー」", en: 'Blade Exhaustion Sign "Mountain Murder"'},
      {id: 19, ja: "尽符「ブラッディマウンテンマーダー」", en: 'Blade Exhaustion Sign "Bloody Mountain Murder"'},
      {id: 20, ja: "尽符「ブラッディマウンテンマーダー」", en: 'Blade Exhaustion Sign "Bloody Mountain Murder"'},
      {id: 21, ja: "春符「サプライズスプリング」", en: 'Spring Sign "Surprise Spring"'},
      {id: 22, ja: "春符「サプライズスプリング」", en: 'Spring Sign "Surprise Spring"'},
      {id: 23, ja: "犬符「野良犬の散歩」", en: 'Dog Sign "Stray Dog\'s Walk"'},
      {id: 24, ja: "犬符「野良犬の散歩」", en: 'Dog Sign "Stray Dog\'s Walk"'},
      {id: 25, ja: "狗符「山狗の散歩」", en: 'Hound Sign "Mountain Hound\'s Walk"'},
      {id: 26, ja: "狗符「山狗の散歩」", en: 'Hound Sign "Mountain Hound\'s Walk"'},
      {id: 27, ja: "独楽「コマ犬回し」", en: 'Spinning Top "Koma-Inu Spin"'},
      {id: 28, ja: "独楽「コマ犬回し」", en: 'Spinning Top "Koma-Inu Spin"'},
      {id: 29, ja: "独楽「コマ犬回し」", en: 'Spinning Top "Koma-Inu Spin"'},
      {id: 30, ja: "独楽「カールアップアンドダイ」", en: 'Spinning Top "Curl Up and Die"'},
      {id: 31, ja: "狛符「独り阿吽の呼吸」", en: 'Koma Sign "Solitary A-Um Breathing"'},
      {id: 32, ja: "狛符「独り阿吽の呼吸」", en: 'Koma Sign "Solitary A-Um Breathing"'},
      {id: 33, ja: "狛符「独り阿吽の呼吸」", en: 'Koma Sign "Solitary A-Um Breathing"'},
      {id: 34, ja: "狛符「独り阿吽の呼吸」", en: 'Koma Sign "Solitary A-Um Breathing"'},
      {id: 35, ja: "魔符「インスタントボーディ」", en: 'Magic Sign "Instant Bodhi"'},
      {id: 36, ja: "魔符「インスタントボーディ」", en: 'Magic Sign "Instant Bodhi"'},
      {id: 37, ja: "魔符「即席菩提」", en: 'Magic Sign "Bodhi in an Instant"'},
      {id: 38, ja: "魔符「即席菩提」", en: 'Magic Sign "Bodhi in an Instant"'},
      {id: 39, ja: "魔符「バレットゴーレム」", en: 'Magic Sign "Bullet Golem"'},
      {id: 40, ja: "魔符「バレットゴーレム」", en: 'Magic Sign "Bullet Golem"'},
      {id: 41, ja: "魔符「ペットの巨大弾生命体」", en: 'Magic Sign "Gigantic Pet Bullet Lifeform"'},
      {id: 42, ja: "魔符「ペットの巨大弾生命体」", en: 'Magic Sign "Gigantic Pet Bullet Lifeform"'},
      {id: 43, ja: "地蔵「クリミナルサルヴェイション」", en: 'Jizo "Criminal Salvation"'},
      {id: 44, ja: "地蔵「クリミナルサルヴェイション」", en: 'Jizo "Criminal Salvation"'},
      {id: 45, ja: "地蔵「業火救済」", en: 'Jizo "Hellfire Salvation"'},
      {id: 46, ja: "地蔵「業火救済」", en: 'Jizo "Hellfire Salvation"'},
      {id: 47, ja: "竹符「バンブースピアダンス」", en: 'Bamboo Sign "Bamboo Spear Dance"'},
      {id: 48, ja: "竹符「バンブースピアダンス」", en: 'Bamboo Sign "Bamboo Spear Dance"'},
      {id: 49, ja: "竹符「バンブークレイジーダンス」", en: 'Bamboo Sign "Bamboo Crazy Dance"'},
      {id: 50, ja: "竹符「バンブークレイジーダンス」", en: 'Bamboo Sign "Bamboo Crazy Dance"'},
      {id: 51, ja: "茗荷「フォゲットユアネーム」", en: 'Myōga Ginger "Forget Your Name"'},
      {id: 52, ja: "茗荷「フォゲットユアネーム」", en: 'Myōga Ginger "Forget Your Name"'},
      {id: 53, ja: "茗荷「フォゲットユアネーム」", en: 'Myōga Ginger "Forget Your Name"'},
      {id: 54, ja: "茗荷「フォゲットユアネーム」", en: 'Myōga Ginger "Forget Your Name"'},
      {id: 55, ja: "笹符「タナバタスターフェスティバル」", en: 'Broadleaf Sign "Tanabata Star Festival"'},
      {id: 56, ja: "笹符「タナバタスターフェスティバル」", en: 'Broadleaf Sign "Tanabata Star Festival"'},
      {id: 57, ja: "笹符「タナバタスターフェスティバル」", en: 'Broadleaf Sign "Tanabata Star Festival"'},
      {id: 58, ja: "笹符「タナバタスターフェスティバル」", en: 'Broadleaf Sign "Tanabata Star Festival"'},
      {id: 59, ja: "冥加「ビハインドユー」", en: 'Myōga Blessing "Behind You"'},
      {id: 60, ja: "冥加「ビハインドユー」", en: 'Myōga Blessing "Behind You"'},
      {id: 61, ja: "冥加「ビハインドユー」", en: 'Myōga Blessing "Behind You"'},
      {id: 62, ja: "冥加「ビハインドユー」", en: 'Myōga Blessing "Behind You"'},
      {id: 63, ja: "舞符「ビハインドフェスティバル」", en: 'Dance Sign "Behind Festival"'},
      {id: 64, ja: "舞符「ビハインドフェスティバル」", en: 'Dance Sign "Behind Festival"'},
      {id: 65, ja: "舞符「ビハインドフェスティバル」", en: 'Dance Sign "Behind Festival"'},
      {id: 66, ja: "舞符「ビハインドフェスティバル」", en: 'Dance Sign "Behind Festival"'},
      {id: 67, ja: "狂舞「テングオドシ」", en: 'Mad Dance "Tengu-odoshi"'},
      {id: 68, ja: "狂舞「テングオドシ」", en: 'Mad Dance "Tengu-odoshi"'},
      {id: 69, ja: "狂舞「狂乱天狗怖し」", en: 'Mad Dance "Frenzied Tengu-Frightening"'},
      {id: 70, ja: "狂舞「狂乱天狗怖し」", en: 'Mad Dance "Frenzied Tengu-Frightening"'},
      {id: 71, ja: "後符「秘神の後光」", en: 'Back Sign "Halo of the Secret God"'},
      {id: 72, ja: "後符「秘神の後光」", en: 'Back Sign "Halo of the Secret God"'},
      {id: 73, ja: "後符「秘神の後光」", en: 'Back Sign "Halo of the Secret God"'},
      {id: 74, ja: "後符「絶対秘神の後光」", en: 'Back Sign "Halo of the Absolute Secret God"'},
      {id: 75, ja: "裏夏「スコーチ・バイ・ホットサマー」", en: 'Hidden Summer "Scorch By Hot Summer"'},
      {id: 76, ja: "裏夏「スコーチ・バイ・ホットサマー」", en: 'Hidden Summer "Scorch By Hot Summer"'},
      {id: 77, ja: "裏夏「異常猛暑の焦土」", en: 'Hidden Summer "Scorched Earth of Abnormal Intense Heat"'},
      {id: 78, ja: "裏夏「異常猛暑の焦土」", en: 'Hidden Summer "Scorched Earth of Abnormal Intense Heat"'},
      {id: 79, ja: "裏秋「ダイ・オブ・ファミン」", en: 'Hidden Fall "Die of Famine"'},
      {id: 80, ja: "裏秋「ダイ・オブ・ファミン」", en: 'Hidden Fall "Die of Famine"'},
      {id: 81, ja: "裏秋「異常枯死の餓鬼」", en: 'Hidden Fall "Preta of Abnormal Blight"'},
      {id: 82, ja: "裏秋「異常枯死の餓鬼」", en: 'Hidden Fall "Preta of Abnormal Blight"'},
      {id: 83, ja: "裏冬「ブラックスノーマン」", en: 'Hidden Winter "Black Snowman"'},
      {id: 84, ja: "裏冬「ブラックスノーマン」", en: 'Hidden Winter "Black Snowman"'},
      {id: 85, ja: "裏冬「異常降雪の雪だるま」", en: 'Hidden Winter "Snowman of Abnormal Snowfall"'},
      {id: 86, ja: "裏冬「異常降雪の雪だるま」", en: 'Hidden Winter "Snowman of Abnormal Snowfall"'},
      {id: 87, ja: "裏春「エイプリルウィザード」", en: 'Hidden Spring "April Wizard"'},
      {id: 88, ja: "裏春「エイプリルウィザード」", en: 'Hidden Spring "April Wizard"'},
      {id: 89, ja: "裏春「異常落花の魔術使い」", en: 'Hidden Spring "Black Magician of Abnormal Falling Petals"'},
      {id: 90, ja: "裏春「異常落花の魔術使い」", en: 'Hidden Spring "Black Magician of Abnormal Falling Petals"'},
      {id: 91, ja: "「裏・ブリージーチェリーブロッサム」", en: '"Hidden Breezy Cherry Blossom"'},
      {id: 92, ja: "「裏・ブリージーチェリーブロッサム」", en: '"Hidden Breezy Cherry Blossom"'},
      {id: 93, ja: "「裏・ブリージーチェリーブロッサム」", en: '"Hidden Breezy Cherry Blossom"'},
      {id: 94, ja: "「裏・ブリージーチェリーブロッサム」", en: '"Hidden Breezy Cherry Blossom"'},
      {id: 95, ja: "「裏・パーフェクトサマーアイス」", en: '"Hidden Perfect Summer Ice"'},
      {id: 96, ja: "「裏・パーフェクトサマーアイス」", en: '"Hidden Perfect Summer Ice"'},
      {id: 97, ja: "「裏・パーフェクトサマーアイス」", en: '"Hidden Perfect Summer Ice"'},
      {id: 98, ja: "「裏・パーフェクトサマーアイス」", en: '"Hidden Perfect Summer Ice"'},
      {id: 99, ja: "「裏・クレイジーフォールウィンド」", en: '"Hidden Crazy Fall Wind"'},
      {id: 100, ja: "「裏・クレイジーフォールウィンド」", en: '"Hidden Crazy Fall Wind"'},
      {id: 101, ja: "「裏・クレイジーフォールウィンド」", en: '"Hidden Crazy Fall Wind"'},
      {id: 102, ja: "「裏・クレイジーフォールウィンド」", en: '"Hidden Crazy Fall Wind"'},
      {id: 103, ja: "「裏・エクストリームウィンター」", en: '"Hidden Extreme Winter"'},
      {id: 104, ja: "「裏・エクストリームウィンター」", en: '"Hidden Extreme Winter"'},
      {id: 105, ja: "「裏・エクストリームウィンター」", en: '"Hidden Extreme Winter"'},
      {id: 106, ja: "「裏・エクストリームウィンター」", en: '"Hidden Extreme Winter"'},
      {id: 107, ja: "鼓舞「パワフルチアーズ」", en: 'Drum Dance "Powerful Cheers"'},
      {id: 108, ja: "狂舞「クレイジーバックダンス」", en: 'Mad Dance "Crazy Backup Dance"'},
      {id: 109, ja: "弾舞「二つ目の台風」", en: 'Bullet Dance "Twin Typhoons"'},
      {id: 110, ja: "秘儀「リバースインヴォーカー」", en: 'Secret Ceremony "Reverse Invoker"'},
      {id: 111, ja: "秘儀「裏切りの後方射撃」", en: 'Secret Ceremony "Rear Shots of Betrayal"'},
      {id: 112, ja: "秘儀「弾幕の玉繭」", en: 'Secret Ceremony "Danmaku Dupion"'},
      {id: 113, ja: "秘儀「穢那の火」", en: 'Secret Ceremony "Fire of Ena"'},
      {id: 114, ja: "秘儀「後戸の狂言」", en: 'Secret Ceremony "Kyōgen of the Back Door"'},
      {id: 115, ja: "秘儀「マターラドゥッカ」", en: 'Secret Ceremony "Matarah Dukkha"'},
      {id: 116, ja: "秘儀「七星の剣」", en: 'Secret Ceremony "Sword of the Seven Stars"'},
      {id: 117, ja: "秘儀「無縁の芸能者」", en: 'Secret Ceremony "Performers Unattached to Society"'},
      {id: 118, ja: "「背面の暗黒猿楽」", en: '"The Back Face\'s Dark Sarugaku"'},
      {id: 119, ja: "「アナーキーバレットヘル」", en: '"Anarchy Bullet Hell"'},
    ]
  }
</script>