<script setup lang="ts">
  export function th08SpellCard(spellCardId: number){
    const spellCardMap=[
      {id: 1 ,ja: "蛍符「地上の流星」", en: 'Firefly Sign "Earthly Meteor"'},
      {id: 2 ,ja: "蛍符「地上の彗星」", en: 'Firefly Sign "Earthly Comet"'},
      {id: 3 ,ja: "灯符「ファイヤフライフェノメノン」", en: 'Lamp Sign "Firefly Phenomenon"'},
      {id: 4 ,ja: "灯符「ファイヤフライフェノメノン」", en: 'Lamp Sign "Firefly Phenomenon"'},
      {id: 5 ,ja: "灯符「ファイヤフライフェノメノン」", en: 'Lamp Sign "Firefly Phenomenon"'},
      {id: 6, ja: "灯符「ファイヤフライフェノメノン」", en: 'Lamp Sign "Firefly Phenomenon"'},
      {id: 7, ja: "蠢符「リトルバグ」", en: 'Wriggle Sign "Little Bug"'},
      {id: 8 ,ja: "蠢符「リトルバグストーム」", en: 'Wriggle Sign "Little Bug Storm"'},
      {id: 9 ,ja: "蠢符「ナイトバグストーム」", en: 'Wriggle Sign "Nightbug Storm"'},
      {id: 10 ,ja: "蠢符「ナイトバグトルネード」", en: 'Wriggle Sign "Nightbug Tornado"'},
      {id: 11 ,ja: "隠蟲「永夜蟄居」", en: 'Hidden Bug "Endless Night Seclusion"'},
      {id: 12 ,ja: "隠蟲「永夜蟄居」", en: 'Hidden Bug "Endless Night Seclusion"'},
      {id: 13 ,ja: "隠蟲「永夜蟄居」", en: 'Hidden Bug "Endless Night Seclusion"'},
      {id: 14 ,ja: "声符「梟の夜鳴声」", en: 'Vocal Sign "Hooting in the Night"'},
      {id: 15 ,ja: "声符「梟の夜鳴声」", en: 'Vocal Sign "Hooting in the Night"'},
      {id: 16 ,ja: "声符「木菟咆哮」", en: 'Vocal Sign "Howl of the Horned Owl"'},
      {id: 17 ,ja: "声符「木菟咆哮」", en: 'Vocal Sign "Howl of the Horned Owl"'},
      {id: 18 ,ja: "蛾符「天蛾の蠱道」", en: 'Moth Sign "Hawk Moth\'s Insect Curse"'},
      {id: 19 ,ja: "蛾符「天蛾の蠱道」", en: 'Moth Sign "Hawk Moth\'s Insect Curse"'},
      {id: 20 ,ja: "毒符「毒蛾の鱗粉」", en: 'Toxin Sign "Poisonous Moth\'s Scales"'},
      {id: 21 ,ja: "猛毒「毒蛾の暗闇演舞」", en: 'Deadly Toxin "Poisonous Moth\'s Dance in the Dark"'},
      {id: 22 ,ja: "鷹符「イルスタードダイブ」", en: 'Hawk Sign "Ill-Starred Dive"'},
      {id: 23 ,ja: "鷹符「イルスタードダイブ」", en: 'Hawk Sign "Ill-Starred Dive"'},
      {id: 24 ,ja: "鷹符「イルスタードダイブ」", en: 'Hawk Sign "Ill-Starred Dive"'},
      {id: 25 ,ja: "鷹符「イルスタードダイブ」", en: 'Hawk Sign "Ill-Starred Dive"'},
      {id: 26 ,ja: "夜盲「夜雀の歌」", en: 'Night-Blindness "Song of the Night Sparrow"'},
      {id: 27 ,ja: "夜盲「夜雀の歌」", en: 'Night-Blindness "Song of the Night Sparrow"'},
      {id: 28 ,ja: "夜盲「夜雀の歌」", en: 'Night-Blindness "Song of the Night Sparrow"'},
      {id: 29 ,ja: "夜盲「夜雀の歌」", en: 'Night-Blindness "Song of the Night Sparrow"'},
      {id: 30 ,ja: "夜雀「真夜中のコーラスマスター」", en: 'Night-Sparrow "Midnight Chorus-Master"'},
      {id: 31 ,ja: "夜雀「真夜中のコーラスマスター」", en: 'Night-Sparrow "Midnight Chorus-Master"'},
      {id: 32 ,ja: "夜雀「真夜中のコーラスマスター」", en: 'Night-Sparrow "Midnight Chorus-Master"'},
      {id: 33 ,ja: "産霊「ファーストピラミッド」", en: 'Spiritual Birth "First Pyramid"'},
      {id: 34 ,ja: "産霊「ファーストピラミッド」", en: 'Spiritual Birth "First Pyramid"'},
      {id: 35 ,ja: "産霊「ファーストピラミッド」", en: 'Spiritual Birth "First Pyramid"'},
      {id: 36 ,ja: "産霊「ファーストピラミッド」", en: 'Spiritual Birth "First Pyramid"'},
      {id: 37 ,ja: "始符「エフェメラリティ137」", en: 'Origin Sign "Ephemerality 137"'},
      {id: 38 ,ja: "始符「エフェメラリティ137」", en: 'Origin Sign "Ephemerality 137"'},
      {id: 39 ,ja: "始符「エフェメラリティ137」", en: 'Origin Sign "Ephemerality 137"'},
      {id: 40 ,ja: "野符「武烈クライシス」", en: 'Ambition Sign "Buretsu Crisis"'},
      {id: 41 ,ja: "野符「将門クライシス」", en: 'Ambition Sign "Masakado Crisis"'},
      {id: 42 ,ja: "野符「義満クライシス」", en: 'Ambition Sign "Yoshimitsu Crisis"'},
      {id: 43 ,ja: "野符「GHQクライシス」", en: 'Ambition Sign "General Headquarters Crisis"'},
      {id: 44 ,ja: "国符「三種の神器　剣」", en: 'Land Sign "Three Sacred Treasures - Sword"'},
      {id: 45 ,ja: "国符「三種の神器　玉」", en: 'Land Sign "Three Sacred Treasures - Orb"'},
      {id: 46 ,ja: "国符「三種の神器　鏡」", en: 'Land Sign "Three Sacred Treasures - Mirror"'},
      {id: 47 ,ja: "国体「三種の神器　郷」", en: 'Land Scheme "Three Sacred Treasures - Country"'},
      {id: 48 ,ja: "終符「幻想天皇」", en: 'Ending Sign "Phantasmal Emperor"'},
      {id: 49 ,ja: "終符「幻想天皇」", en: 'Ending Sign "Phantasmal Emperor"'},
      {id: 50 ,ja: "虚史「幻想郷伝説」", en: 'Pseudo-History "The Legend of Gensokyo"'},
      {id: 51 ,ja: "虚史「幻想郷伝説」", en: 'Pseudo-History "The Legend of Gensokyo"'},
      {id: 52 ,ja: "未来「高天原」", en: 'Future "Gods\' Realm"'},
      {id: 53 ,ja: "未来「高天原」", en: 'Future "Gods\' Realm"'},
      {id: 54 ,ja: "未来「高天原」", en: 'Future "Gods\' Realm"'},
      {id: 55 ,ja: "夢符「二重結界」", en: 'Dream Sign "Duplex Barrier"'},
      {id: 56 ,ja: "夢符「二重結界」", en: 'Dream Sign "Duplex Barrier"'},
      {id: 57 ,ja: "夢境「二重大結界」", en: 'Dream Land "Great Duplex Barrier"'},
      {id: 58 ,ja: "夢境「二重大結界」", en: 'Dream Land "Great Duplex Barrier"'},
      {id: 59 ,ja: "霊符「夢想封印　散」", en: 'Spirit Sign "Fantasy Seal -Spread-"'},
      {id: 60 ,ja: "霊符「夢想封印　散」", en: 'Spirit Sign "Fantasy Seal -Spread-"'},
      {id: 61 ,ja: "散霊「夢想封印　寂」", en: 'Scattered Spirit "Fantasy Seal -Worn-"'},
      {id: 62 ,ja: "散霊「夢想封印　寂」", en: 'Scattered Spirit "Fantasy Seal -Worn-"'},
      {id: 63 ,ja: "夢符「封魔陣」", en: 'Dream Sign "Evil-Sealing Circle"'},
      {id: 64 ,ja: "夢符「封魔陣」", en: 'Dream Sign "Evil-Sealing Circle"'},
      {id: 65 ,ja: "神技「八方鬼縛陣」", en: 'Divine Arts "Omnidirectional Oni-Binding Circle"'},
      {id: 66 ,ja: "神技「八方龍殺陣」", en: 'Divine Arts "Omnidirectional Oni-Binding Circle"'},
      {id: 67 ,ja: "霊符「夢想封印　集」", en: 'Spirit Sign "Fantasy Seal -Concentrate-"'},
      {id: 68 ,ja: "霊符「夢想封印　集」", en: 'Spirit Sign "Fantasy Seal -Concentrate-"'},
      {id: 69 ,ja: "回霊「夢想封印　侘」", en: 'Migrating Spirit "Fantasy Seal -Marred-"'},
      {id: 70 ,ja: "回霊「夢想封印　侘」", en: 'Migrating Spirit "Fantasy Seal -Marred-"'},
      {id: 71 ,ja: "境界「二重弾幕結界」", en: 'Boundary "Duplex Danmaku Barrier"'},
      {id: 72 ,ja: "境界「二重弾幕結界」", en: 'Boundary "Duplex Danmaku Barrier"'},
      {id: 73 ,ja: "大結界「博麗弾幕結界」", en: 'Great Barrier "Hakurei Danmaku Barrier"'},
      {id: 74 ,ja: "大結界「博麗弾幕結界」", en: 'Great Barrier "Hakurei Danmaku Barrier"'},
      {id: 75 ,ja: "神霊「夢想封印　瞬」", en: 'Divine Spirit "Fantasy Seal -Blink-"'},
      {id: 76 ,ja: "神霊「夢想封印　瞬」", en: 'Divine Spirit "Fantasy Seal -Blink-"'},
      {id: 77 ,ja: "神霊「夢想封印　瞬」", en: 'Divine Spirit "Fantasy Seal -Blink-"'},
      {id: 78 ,ja: "魔符「ミルキーウェイ」", en: 'Magic Sign "Milky Way"'},
      {id: 79 ,ja: "魔符「ミルキーウェイ」", en: 'Magic Sign "Milky Way"'},
      {id: 80 ,ja: "魔空「アステロイドベルト」", en: 'Magic Space "Asteroid Belt"'},
      {id: 81 ,ja: "魔空「アステロイドベルト」", en: 'Magic Space "Asteroid Belt"'},
      {id: 82 ,ja: "魔符「スターダストレヴァリエ」", en: 'Magic Sign "Stardust Reverie"'},
      {id: 83 ,ja: "魔符「スターダストレヴァリエ」", en: 'Magic Sign "Stardust Reverie"'},
      {id: 84 ,ja: "黒魔「イベントホライズン」", en: 'Black Magic "Event Horizon"'},
      {id: 85 ,ja: "黒魔「イベントホライズン」", en: 'Black Magic "Event Horizon"'},
      {id: 86 ,ja: "恋符「ノンディレクショナルレーザー」", en: 'Love Sign "Non-Directional Laser"'},
      {id: 87 ,ja: "恋符「ノンディレクショナルレーザー」", en: 'Love Sign "Non-Directional Laser"'},
      {id: 88 ,ja: "恋風「スターライトタイフーン」", en: 'Love Storm "Starlight Typhoon"'},
      {id: 89 ,ja: "恋風「スターライトタイフーン」", en: 'Love Storm "Starlight Typhoon"'},
      {id: 90 ,ja: "恋符「マスタースパーク」", en: 'Love Sign "Master Spark"'},
      {id: 91 ,ja: "恋符「マスタースパーク」", en: 'Love Sign "Master Spark"'},
      {id: 92 ,ja: "恋心「ダブルスパーク」", en: 'Loving Heart "Double Spark"'},
      {id: 93 ,ja: "恋心「ダブルスパーク」", en: 'Loving Heart "Double Spark"'},
      {id: 94 ,ja: "光符「アースライトレイ」", en: 'Light Sign "Earthlight Ray"'},
      {id: 95 ,ja: "光符「アースライトレイ」", en: 'Light Sign "Earthlight Ray"'},
      {id: 96 ,ja: "光撃「シュート・ザ・ムーン」", en: 'Light Blast "Shoot the Moon"'},
      {id: 97 ,ja: "光撃「シュート・ザ・ムーン」", en: 'Light Blast "Shoot the Moon"'},
      {id: 98 ,ja: "魔砲「ファイナルスパーク」", en: 'Magicannon "Final Spark"'},
      {id: 99 ,ja: "魔砲「ファイナルスパーク」", en: 'Magicannon "Final Spark"'},
      {id: 100 ,ja: "魔砲「ファイナルマスタースパーク」", en: 'Magicannon "Final Master Spark"'},
      {id: 101 ,ja: "波符「赤眼催眠(マインドシェイカー)」", en: 'Wave Sign "Red-Eyed Hypnosis (Mind Shaker)"'},
      {id: 102 ,ja: "波符「赤眼催眠(マインドシェイカー)」", en: 'Wave Sign "Red-Eyed Hypnosis (Mind Shaker)"'},
      {id: 103 ,ja: "幻波「赤眼催眠(マインドブローイング)」", en: 'Illusion Wave "Red-Eyed Hypnosis (Mind Blowing)"'},
      {id: 104 ,ja: "幻波「赤眼催眠(マインドブローイング)」", en: 'Illusion Wave "Red-Eyed Hypnosis (Mind Blowing)"'},
      {id: 105 ,ja: "狂符「幻視調律(ビジョナリチューニング)」", en: 'Lunatic Sign "Hallucinogenic Tuning (Visionary Tuning)"'},
      {id: 106 ,ja: "狂符「幻視調律(ビジョナリチューニング)」", en: 'Lunatic Sign "Hallucinogenic Tuning (Visionary Tuning)"'},
      {id: 107 ,ja: "狂視「狂視調律(イリュージョンシーカー)」", en: 'Lunatic Gaze "Lunatic Stare Tuning (Illusion Seeker)"'},
      {id: 108 ,ja: "狂視「狂視調律(イリュージョンシーカー)」", en: 'Lunatic Gaze "Lunatic Stare Tuning (Illusion Seeker)"'},
      {id: 109 ,ja: "懶符「生神停止(アイドリングウェーブ)」", en: 'Loafing Sign "Life & Spirit Stopping (Idling Wave)"'},
      {id: 110 ,ja: "懶符「生神停止(アイドリングウェーブ)」", en: 'Loafing Sign "Life & Spirit Stopping (Idling Wave)"'},
      {id: 111 ,ja: "懶惰「生神停止(マインドストッパー)」", en: 'Indolence "Life & Spirit Stopping (Mind Stopper)"'},
      {id: 112 ,ja: "懶惰「生神停止(マインドストッパー)」", en: 'Indolence "Life & Spirit Stopping (Mind Stopper)"'},
      {id: 113 ,ja: "散符「真実の月(インビジブルフルムーン)」", en: 'Spread Sign "Moon of Truth (Invisible Full Moon)"'},
      {id: 114 ,ja: "散符「真実の月(インビジブルフルムーン)」", en: 'Spread Sign "Moon of Truth (Invisible Full Moon)"'},
      {id: 115 ,ja: "散符「真実の月(インビジブルフルムーン)」", en: 'Spread Sign "Moon of Truth (Invisible Full Moon)"'},
      {id: 116 ,ja: "散符「真実の月(インビジブルフルムーン)」", en: 'Spread Sign "Moon of Truth (Invisible Full Moon)"'},
      {id: 117 ,ja: "月眼「月兎遠隔催眠術(テレメスメリズム)」", en: 'Lunar Eyes "Lunar Rabbit\'s Remote Mesmerism (Tele-Mesmerism)"'},
      {id: 118 ,ja: "月眼「月兎遠隔催眠術(テレメスメリズム)」", en: 'Lunar Eyes "Lunar Rabbit\'s Remote Mesmerism (Tele-Mesmerism)"'},
      {id: 119 ,ja: "月眼「月兎遠隔催眠術(テレメスメリズム)」", en: 'Lunar Eyes "Lunar Rabbit\'s Remote Mesmerism (Tele-Mesmerism)"'},
      {id: 120 ,ja: "天丸「壺中の天地」", en: 'Spacesphere "Earth in a Pot"'},
      {id: 121 ,ja: "天丸「壺中の天地」", en: 'Spacesphere "Earth in a Pot"'},
      {id: 122 ,ja: "天丸「壺中の天地」", en: 'Spacesphere "Earth in a Pot"'},
      {id: 123 ,ja: "天丸「壺中の天地」", en: 'Spacesphere "Earth in a Pot"'},
      {id: 124 ,ja: "覚神「神代の記憶」", en: 'Awakened God "Memories of the Age of the Gods"'},
      {id: 125 ,ja: "覚神「神代の記憶」", en: 'Awakened God "Memories of the Age of the Gods"'},
      {id: 126 ,ja: "神符「天人の系譜」", en: 'God Sign "Genealogy of the Celestials"'},
      {id: 127 ,ja: "神符「天人の系譜」", en: 'God Sign "Genealogy of the Celestials"'},
      {id: 128 ,ja: "蘇活「生命遊戯　-ライフゲーム-」", en: 'Revival "Seimei Yūgi -Life Game-"'},
      {id: 129 ,ja: "蘇活「生命遊戯　-ライフゲーム-」", en: 'Revival "Seimei Yūgi -Life Game-"'},
      {id: 130 ,ja: "蘇生「ライジングゲーム」", en: 'Resurrection "Rising Game"'},
      {id: 131 ,ja: "蘇生「ライジングゲーム」", en: 'Resurrection "Rising Game"'},
      {id: 132 ,ja: "操神「オモイカネディバイス」", en: 'Leading God "Omoikane\'s Device"'},
      {id: 133 ,ja: "操神「オモイカネディバイス」", en: 'Leading God "Omoikane\'s Device"'},
      {id: 134 ,ja: "神脳「オモイカネブレイン」", en: 'Mind of God "Omoikane\'s Brain"'},
      {id: 135 ,ja: "神脳「オモイカネブレイン」", en: 'Mind of God "Omoikane\'s Brain"'},
      {id: 136 ,ja: "天呪「アポロ１３」", en: 'Curse of the Heavens "Apollo 13"'},
      {id: 137 ,ja: "天呪「アポロ１３」", en: 'Curse of the Heavens "Apollo 13"'},
      {id: 138 ,ja: "天呪「アポロ１３」", en: 'Curse of the Heavens "Apollo 13"'},
      {id: 139 ,ja: "天呪「アポロ１３」", en: 'Curse of the Heavens "Apollo 13"'},
      {id: 140 ,ja: "秘術「天文密葬法」", en: 'Esoterica "Astronomical Entombing"'},
      {id: 141 ,ja: "秘術「天文密葬法」", en: 'Esoterica "Astronomical Entombing"'},
      {id: 142 ,ja: "秘術「天文密葬法」", en: 'Esoterica "Astronomical Entombing"'},
      {id: 143 ,ja: "秘術「天文密葬法」", en: 'Esoterica "Astronomical Entombing"'},
      {id: 144 ,ja: "禁薬「蓬莱の薬」", en: 'Forbidden Elixir "Hourai Elixir"'},
      {id: 145 ,ja: "禁薬「蓬莱の薬」", en: 'Forbidden Elixir "Hourai Elixir"'},
      {id: 146 ,ja: "禁薬「蓬莱の薬」", en: 'Forbidden Elixir "Hourai Elixir"'},
      {id: 147 ,ja: "禁薬「蓬莱の薬」", en: 'Forbidden Elixir "Hourai Elixir"'},
      {id: 148 ,ja: "薬符「壺中の大銀河」", en: 'Medicine Sign "Galaxy in a Pot"'},
      {id: 149 ,ja: "薬符「壺中の大銀河」", en: 'Medicine Sign "Galaxy in a Pot"'},
      {id: 150 ,ja: "薬符「壺中の大銀河」", en: 'Medicine Sign "Galaxy in a Pot"'},
      {id: 151 ,ja: "薬符「壺中の大銀河」", en: 'Medicine Sign "Galaxy in a Pot"'},
      {id: 152 ,ja: "難題「龍の頸の玉 -五色の弾丸-」", en: "Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\""},
      {id: 153 ,ja: "難題「龍の頸の玉 -五色の弾丸-」", en: "Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\""},
      {id: 154 ,ja: "神宝「ブリリアントドラゴンバレッタ」", en: 'Divine Treasure "Brilliant Dragon Bullet"'},
      {id: 155 ,ja: "神宝「ブリリアントドラゴンバレッタ」", en: 'Divine Treasure "Brilliant Dragon Bullet"'},
      {id: 156 ,ja: "難題「仏の御石の鉢 -砕けぬ意思-」", en: 'Impossible Request "Buddha\'s Stone Bowl -Indomitable Will-"'},
      {id: 157 ,ja: "難題「仏の御石の鉢 -砕けぬ意思-」", en: 'Impossible Request "Buddha\'s Stone Bowl -Indomitable Will-"'},
      {id: 158 ,ja: "神宝「ブディストダイアモンド」", en: 'Divine Treasure "Buddhist Diamond"'},
      {id: 159 ,ja: "神宝「ブディストダイアモンド」", en: 'Divine Treasure "Buddhist Diamond"'},
      {id: 160 ,ja: "難題「火鼠の皮衣 -焦れぬ心-」", en: 'Impossible Request "Robe of Fire Rat -Patient Mind-"'},
      {id: 161 ,ja: "難題「火鼠の皮衣 -焦れぬ心-」", en: 'Impossible Request "Robe of Fire Rat -Patient Mind-"'},
      {id: 162 ,ja: "神宝「サラマンダーシールド」", en: 'Divine Treasure "Salamander Shield"'},
      {id: 163 ,ja: "神宝「サラマンダーシールド」", en: 'Divine Treasure "Salamander Shield"'},
      {id: 164 ,ja: "難題「燕の子安貝 -永命線-」", en: 'Impossible Request "Swallow\'s Cowrie Shell -Everlasting Life-"'},
      {id: 165 ,ja: "難題「燕の子安貝 -永命線-」", en: 'Impossible Request "Swallow\'s Cowrie Shell -Everlasting Life-"'},
      {id: 166 ,ja: "神宝「ライフスプリングインフィニティ」", en: 'Divine Treasure "Life Spring Infinity"'},
      {id: 167 ,ja: "神宝「ライフスプリングインフィニティ」", en: 'Divine Treasure "Life Spring Infinity"'},
      {id: 168 ,ja: "難題「蓬莱の弾の枝 -虹色の弾幕-」", en: 'Impossible Request "Bullet Branch of Hourai -Rainbow Danmaku-"'},
      {id: 169 ,ja: "難題「蓬莱の弾の枝 -虹色の弾幕-」", en: 'Impossible Request "Bullet Branch of Hourai -Rainbow Danmaku-"'},
      {id: 170 ,ja: "神宝「蓬莱の玉の枝 -夢色の郷-」", en: 'Divine Treasure "Jeweled Branch of Hourai -Dreamlike Paradise-"'},
      {id: 171 ,ja: "神宝「蓬莱の玉の枝 -夢色の郷-」", en: 'Divine Treasure "Jeweled Branch of Hourai -Dreamlike Paradise-"'},
      {id: 172 ,ja: "「永夜返し -初月-」", en: '"End of Imperishable Night -New Moon-"'},
      {id: 173 ,ja: "「永夜返し -三日月-」", en: '"End of Imperishable Night -Crescent Moon-"'},
      {id: 174 ,ja: "「永夜返し -上つ弓張-」", en: '"End of Imperishable Night -1st Quarter\'s Moon-"'},
      {id: 175 ,ja: "「永夜返し -待宵-」", en: '"End of Imperishable Night -Matsuyoi-"'},
      {id: 176 ,ja: "「永夜返し -子の刻-」", en: '"End of Imperishable Night -11 o\'Clock-"'},
      {id: 177 ,ja: "「永夜返し -子の二つ-」", en: '"End of Imperishable Night -Half to Midnight-"'},
      {id: 178 ,ja: "「永夜返し -子の三つ-」", en: '"End of Imperishable Night -Midnight-"'},
      {id: 179 ,ja: "「永夜返し -子の四つ-」", en: '"End of Imperishable Night -Half Past Midnight-"'},
      {id: 180 ,ja: "「永夜返し -丑の刻-」", en: '"End of Imperishable Night -1 o\'Clock-"'},
      {id: 181 ,ja: "「永夜返し -丑の二つ-」", en: '"End of Imperishable Night -Half Past 1-"'},
      {id: 182 ,ja: "「永夜返し -丑三つ時-」", en: '"End of Imperishable Night -Dead of Night-"'},
      {id: 183 ,ja: "「永夜返し -丑の四つ-」", en: '"End of Imperishable Night -Half Past 2-"'},
      {id: 184 ,ja: "「永夜返し -寅の刻-」", en: '"End of Imperishable Night -3 o\'Clock-"'},
      {id: 185 ,ja: "「永夜返し -寅の二つ-」", en: '"End of Imperishable Night -Half Past 3-"'},
      {id: 186 ,ja: "「永夜返し -寅の三つ-」", en: '"End of Imperishable Night -4 o\'Clock-"'},
      {id: 187 ,ja: "「永夜返し -寅の四つ-」", en: '"End of Imperishable Night -Half Past 4-"'},
      {id: 188 ,ja: "「永夜返し -朝靄-」", en: '"End of Imperishable Night -Morning Mist-"'},
      {id: 189 ,ja: "「永夜返し -夜明け-」", en: '"End of Imperishable Night -Dawn-"'},
      {id: 190 ,ja: "「永夜返し -明けの明星-」", en: '"End of Imperishable Night -Morning Star-"'},
      {id: 191 ,ja: "「永夜返し -世明け-」", en: '"End of Imperishable Night -Rising World-"'},
      {id: 192 ,ja: "旧史「旧秘境史　-オールドヒストリー-」", en: 'Past "Old History of an Untrodden Land -Old History-"'},
      {id: 193 ,ja: "転世「一条戻り橋」", en: 'Reincarnation "Ichijou Returning Bridge"'},
      {id: 194 ,ja: "新史「新幻想史　-ネクストヒストリー-」", en: 'Future "New History of Fantasy -Next History-"'},
      {id: 195 ,ja: "時効「月のいはかさの呪い」", en: 'Limiting Edict "Curse of Tsuki-no-Iwakasa"'},
      {id: 196 ,ja: "不死「火の鳥　-鳳翼天翔-」", en: 'Undying "Fire Bird -Feng Wing Ascension-"'},
      {id: 197 ,ja: "藤原「滅罪寺院傷」", en: 'Fujiwara "Wounds of Metsuzai Temple"'},
      {id: 198 ,ja: "不死「徐福時空」",en: 'Undying "Xu Fu\'s Dimension"'},
      {id: 199 ,ja: "滅罪「正直者の死」", en: 'Expiation "Honest Man\'s Death"'},
      {id: 200 ,ja: "虚人「ウー」", en: 'Hollow Being "Wu"'},
      {id: 201 ,ja: "不滅「フェニックスの尾」", en: 'Inextinguishable "Phoenix\'s Tail"'},
      {id: 202 ,ja: "蓬莱「凱風快晴　-フジヤマヴォルケイノ-」", en: 'Hourai "South Wind, Clear Sky -Fujiyama Volcano-"'},
      {id: 203 ,ja: "「パゼストバイフェニックス」", en: '"Possessed by Phoenix"'},
      {id: 204 ,ja: "「蓬莱人形」", en: '"Hourai Doll"'},
      {id: 205 ,ja: "「インペリシャブルシューティング」", en: '"Imperishable Shooting"'},
      {id: 206 ,ja: "「季節外れのバタフライストーム」", en: '"Unseasonal Butterfly Storm"'},
      {id: 207 ,ja: "「ブラインドナイトバード」", en: '"Blind Nightbird"'},
      {id: 208 ,ja: "「日出づる国の天子」", en: '"Emperor of the Land of the Rising Sun"'},
      {id: 209 ,ja: "「幻朧月睨(ルナティックレッドアイズ)」", en: '"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)"'},
      {id: 210 ,ja: "「天網蜘網捕蝶の法」", en: '"Heaven Spider\'s Butterfly-Capturing Web"'},
      {id: 211 ,ja: "「蓬莱の樹海」", en: '"Tree-Ocean of Hourai"'},
      {id: 212 ,ja: "「フェニックス再誕」", en: '"Phoenix Rebirth"'},
      {id: 213 ,ja: "「エンシェントデューパー」", en: '"Ancient Duper"'},
      {id: 214 ,ja: "「無何有浄化」", en: '"Total Purification"'},
      {id: 215 ,ja: "「夢想天生」", en: '"Fantasy Nature"'},
      {id: 216 ,ja: "「ブレイジングスター」", en: '"Blazing Star"'},
      {id: 217 ,ja: "「デフレーションワールド」", en: '"Deflation World"'},
      {id: 218 ,ja: "「待宵反射衛星斬」", en: '"Matsuyoi-Reflecting Satellite Slash"'},
      {id: 219 ,ja: "「グランギニョル座の怪人」", en: '"The Phantom of the Grand Guignol"'},
      {id: 220 ,ja: "「スカーレットディスティニー」", en: '"Scarlet Destiny"'},
      {id: 221 ,ja: "「西行寺無余涅槃」", en: '"Saigyouji Parinirvana"'},
      {id: 222 ,ja: "「深弾幕結界　-夢幻泡影-」", en: '"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-"'},
    ]
  }
</script>