<script setup lang="ts">
  export function th13SpellCard(spellCardId: number){
    const spellCardMap=[
      {id: 1 ,ja: "符牒「死蝶の舞」", en:'Symbol "Dance of the Dead Butterflies"'},
      {id: 2 ,ja: "符牒「死蝶の舞」", en:'Symbol "Dance of the Dead Butterflies"'},
      {id: 3 ,ja: "符牒「死蝶の舞　- 桜花 -」", en:'Symbol "Dance of the Dead Butterflies - Cherry Blossoms -"'},
      {id: 4 ,ja: "符牒「死蝶の舞　- 桜花 -」", en:'Symbol "Dance of the Dead Butterflies - Cherry Blossoms -"'},
      {id: 5 ,ja: "幽蝶「ゴーストスポット」", en:'Ghostly Butterfly "Ghost Spot"'},
      {id: 6 ,ja: "幽蝶「ゴーストスポット」", en:'Ghostly Butterfly "Ghost Spot"'},
      {id: 7 ,ja: "幽蝶「ゴーストスポット　- 桜花 -」", en:'Ghostly Butterfly "Ghost Spot - Cherry Blossoms -"'},
      {id: 8 ,ja: "幽蝶「ゴーストスポット　- 桜花 -」", en:'Ghostly Butterfly "Ghost Spot - Cherry Blossoms -"'},
      {id: 9 ,ja: "冥符「常夜桜」", en:'Nether Sign "Endless Evening Cherry Blossoms"'},
      {id: 10, ja: "冥符「常夜桜」", en:'Nether Sign "Endless Evening Cherry Blossoms"'},
      {id: 11, ja: "冥符「常夜桜」", en:'Nether Sign "Endless Evening Cherry Blossoms"'},
      {id: 12, ja: "冥符「常夜桜」", en:'Nether Sign "Endless Evening Cherry Blossoms"'},
      {id: 13, ja: "桜符「西行桜吹雪」", en:'Cherry Blossom Sign "Saigyou Cherry Blossom Blizzard"'},
      {id: 14, ja: "桜符「西行桜吹雪」", en:'Cherry Blossom Sign "Saigyou Cherry Blossom Blizzard"'},
      {id: 15, ja: "響符「マウンテンエコー」", en:'Echo Sign "Mountain Echo"'},
      {id: 16, ja: "響符「マウンテンエコー」", en:'Echo Sign "Mountain Echo"'},
      {id: 17, ja: "響符「マウンテンエコースクランブル」", en:'Echo Sign "Mountain Echo Scramble"'},
      {id: 18, ja: "響符「マウンテンエコースクランブル」", en:'Echo Sign "Mountain Echo Scramble"'},
      {id: 19, ja: "響符「パワーレゾナンス」", en:'Echo Sign "Power Resonance"'},
      {id: 20, ja: "響符「パワーレゾナンス」", en:'Echo Sign "Power Resonance"'},
      {id: 21, ja: "響符「パワーレゾナンス」", en:'Echo Sign "Power Resonance"'},
      {id: 22, ja: "響符「パワーレゾナンス」", en:'Echo Sign "Power Resonance"'},
      {id: 23, ja: "山彦「ロングレンジエコー」", en:'Mountain Echo "Long-Range Echo"'},
      {id: 24, ja: "山彦「ロングレンジエコー」", en:'Mountain Echo "Long-Range Echo"'},
      {id: 25, ja: "山彦「アンプリファイエコー」", en:'Mountain Echo "Amplify Echo"'},
      {id: 26, ja: "山彦「アンプリファイエコー」", en:'Mountain Echo "Amplify Echo"'},
      {id: 27, ja: "大声「チャージドクライ」", en:'Great Voice "Charged Cry"'},
      {id: 28, ja: "大声「チャージドクライ」", en:'Great Voice "Charged Cry"'},
      {id: 29, ja: "大声「チャージドヤッホー」", en:'Great Voice "Charged Yahoo!"'},
      {id: 30, ja: "大声「チャージドヤッホー」", en:'Great Voice "Charged Yahoo!"'},
      {id: 31, ja: "虹符「アンブレラサイクロン」", en:'Rainbow Sign "Umbrella Cyclone"'},
      {id: 32, ja: "虹符「アンブレラサイクロン」", en:'Rainbow Sign "Umbrella Cyclone"'},
      {id: 33, ja: "回復「ヒールバイデザイア」", en:'Recovery "Heal By Desire"'},
      {id: 34, ja: "回復「ヒールバイデザイア」", en:'Recovery "Heal By Desire"'},
      {id: 35, ja: "回復「ヒールバイデザイア」", en:'Recovery "Heal By Desire"'},
      {id: 36, ja: "回復「ヒールバイデザイア」", en:'Recovery "Heal By Desire"'},
      {id: 37, ja: "毒爪「ポイズンレイズ」", en:'Poison Nail "Poison Raze"'},
      {id: 38, ja: "毒爪「ポイズンレイズ」", en:'Poison Nail "Poison Raze"'},
      {id: 39, ja: "毒爪「ポイズンマーダー」", en:'Poison Nail "Poison Murder"'},
      {id: 40, ja: "毒爪「ポイズンマーダー」", en:'Poison Nail "Poison Murder"'},
      {id: 41, ja: "欲符「稼欲霊招来」", en:'Desire Sign "Saved Up Desire Spirit Invitation"'},
      {id: 42, ja: "欲符「稼欲霊招来」", en:'Desire Sign "Saved Up Desire Spirit Invitation"'},
      {id: 43, ja: "欲霊「スコアデザイアイーター」", en:'Desire Spirit "Score Desire Eater"'},
      {id: 44, ja: "欲霊「スコアデザイアイーター」", en:'Desire Spirit "Score Desire Eater"'},
      {id: 45, ja: "邪符「ヤンシャオグイ」", en:'Evil Sign "Yǎng Xiǎoguǐ"'},
      {id: 46, ja: "邪符「グーフンイエグイ」", en:'Evil Sign "Gūhún Yěguǐ"'},
      {id: 47, ja: "邪符「グーフンイエグイ」", en:'Evil Sign "Gūhún Yěguǐ"'},
      {id: 48, ja: "入魔「ゾウフォルゥモォ」", en:'Demonify "Zǒuhuǒ Rùmó"'},
      {id: 49, ja: "入魔「ゾウフォルゥモォ」", en:'Demonify "Zǒuhuǒ Rùmó"'},
      {id: 50, ja: "入魔「ゾウフォルゥモォ」", en:'Demonify "Zǒuhuǒ Rùmó"'},
      {id: 51, ja: "入魔「ゾウフォルゥモォ」", en:'Demonify "Zǒuhuǒ Rùmó"'},
      {id: 52, ja: "降霊「死人タンキー」", en:'Possession "Corpse Tóngjī"'},
      {id: 53, ja: "降霊「死人タンキー」", en:'Possession "Corpse Tóngjī"'},
      {id: 54, ja: "通霊「トンリン芳香」", en:'Spirit Link "Tōnglíng Yoshika"'},
      {id: 55, ja: "通霊「トンリン芳香」", en:'Spirit Link "Tōnglíng Yoshika"'},
      {id: 56, ja: "道符「タオ胎動」", en:'Taoist Sign "Tao Fetal Movement"'},
      {id: 57, ja: "道符「タオ胎動」", en:'Taoist Sign "Tao Fetal Movement"'},
      {id: 58, ja: "道符「タオ胎動」", en:'Taoist Sign "Tao Fetal Movement"'},
      {id: 59, ja: "道符「タオ胎動」", en:'Taoist Sign "Tao Fetal Movement"'},
      {id: 60, ja: "雷矢「ガゴウジサイクロン」", en:'Thunder Arrow "Gagouji\'s Cyclone"'},
      {id: 61, ja: "雷矢「ガゴウジサイクロン」", en:'Thunder Arrow "Gagouji\'s Cyclone"'},
      {id: 62, ja: "雷矢「ガゴウジトルネード」", en:'Thunder Arrow "Gagouji\'s Tornado"'},
      {id: 63, ja: "天符「雨の磐舟」", en:'Heaven Sign "Rainy Iwafune"'},
      {id: 64, ja: "天符「雨の磐舟」", en:'Heaven Sign "Rainy Iwafune"'},
      {id: 65, ja: "天符「天の磐舟よ天へ昇れ」", en:'Heaven Sign "Ame-no-Iwafune, Ascend to Heaven"'},
      {id: 66, ja: "天符「天の磐舟よ天へ昇れ」", en:'Heaven Sign "Ame-no-Iwafune, Ascend to Heaven"'},
      {id: 67, ja: "投皿「物部の八十平瓮」", en:'Throwing Dishes "Mononobe\'s Eighty Saké Cups"'},
      {id: 68, ja: "投皿「物部の八十平瓮」", en:'Throwing Dishes "Mononobe\'s Eighty Saké Cups"'},
      {id: 69, ja: "投皿「物部の八十平瓮」", en:'Throwing Dishes "Mononobe\'s Eighty Saké Cups"'},
      {id: 70, ja: "投皿「物部の八十平瓮」", en:'Throwing Dishes "Mononobe\'s Eighty Saké Cups"'},
      {id: 71, ja: "炎符「廃仏の炎風」", en:'Blaze Sign "Blazing Winds of Haibutsu"'},
      {id: 72, ja: "炎符「廃仏の炎風」", en:'Blaze Sign "Blazing Winds of Haibutsu"'},
      {id: 73, ja: "炎符「桜井寺炎上」", en:'Blaze Sign "Sakurai-ji in Flames"'},
      {id: 74, ja: "炎符「桜井寺炎上」", en:'Blaze Sign "Sakurai-ji in Flames"'},
      {id: 75, ja: "聖童女「大物忌正餐」", en:'Saint Girl "Oomonoimi\'s Dinner"'},
      {id: 76, ja: "聖童女「大物忌正餐」", en:'Saint Girl "Oomonoimi\'s Dinner"'},
      {id: 77, ja: "聖童女「大物忌正餐」", en:'Saint Girl "Oomonoimi\'s Dinner"'},
      {id: 78, ja: "聖童女「大物忌正餐」", en:'Saint Girl "Oomonoimi\'s Dinner"'},
      {id: 79, ja: "名誉「十二階の色彩」", en:'Honor "Colors of Twelve Levels"'},
      {id: 80, ja: "名誉「十二階の色彩」", en:'Honor "Colors of Twelve Levels"'},
      {id: 81, ja: "名誉「十二階の冠位」", en:'Honor "Ranks of Twelve Levels"'},
      {id: 82, ja: "名誉「十二階の冠位」", en:'Honor "Ranks of Twelve Levels"'},
      {id: 83, ja: "仙符「日出ずる処の道士」", en:'Hermit Sign "Taoist of the Land of the Rising Sun"'},
      {id: 84, ja: "仙符「日出ずる処の道士」", en:'Hermit Sign "Taoist of the Land of the Rising Sun"'},
      {id: 85, ja: "仙符「日出ずる処の天子」", en:'Hermit Sign "Emperor of the Land of the Rising Sun"'},
      {id: 86, ja: "仙符「日出ずる処の天子」", en:'Hermit Sign "Emperor of the Land of the Rising Sun"'},
      {id: 87, ja: "召喚「豪族乱舞」", en:'Summon "Royal Clan\'s Chaotic Dance"'},
      {id: 88, ja: "召喚「豪族乱舞」", en:'Summon "Royal Clan\'s Chaotic Dance"'},
      {id: 89, ja: "召喚「豪族乱舞」", en:'Summon "Royal Clan\'s Chaotic Dance"'},
      {id: 90, ja: "召喚「豪族乱舞」", en:'Summon "Royal Clan\'s Chaotic Dance"'},
      {id: 91, ja: "秘宝「斑鳩寺の天球儀」", en:'Secret Treasure "Armillary Sphere of Ikaruga-dera"'},
      {id: 92, ja: "秘宝「斑鳩寺の天球儀」", en:'Secret Treasure "Armillary Sphere of Ikaruga-dera"'},
      {id: 93, ja: "秘宝「斑鳩寺の天球儀」", en:'Secret Treasure "Armillary Sphere of Ikaruga-dera"'},
      {id: 94, ja: "秘宝「聖徳太子のオーパーツ」", en:'Secret Treasure "Prince Shotoku\'s Out-of-Place Artifact"'},
      {id: 95, ja: "光符「救世観音の光後光」", en:'Light Sign "Halo of the Guse Kannon"'},
      {id: 96, ja: "光符「救世観音の光後光」", en:'Light Sign "Halo of the Guse Kannon"'},
      {id: 97, ja: "光符「グセフラッシュ」", en:'Light Sign "Guse Flash"'},
      {id: 98, ja: "光符「グセフラッシュ」", en:'Light Sign "Guse Flash"'},
      {id: 99, ja: "眼光「十七条のレーザー」", en:'Discernment "Lasers of Seventeen Articles"'},
      {id: 100, ja: "眼光「十七条のレーザー」", en:'Discernment "Lasers of Seventeen Articles"'},
      {id: 101, ja: "神光「逆らう事なきを宗とせよ」", en:'Divine Light "Honor the Avoidance of Defiance"'},
      {id: 102, ja: "神光「逆らう事なきを宗とせよ」", en:'Divine Light "Honor the Avoidance of Defiance"'},
      {id: 103, ja: "「星降る神霊廟」", en:'"Falling Stars on Divine Spirit Mausoleum"'},
      {id: 104, ja: "「星降る神霊廟」", en:'"Falling Stars on Divine Spirit Mausoleum"'},
      {id: 105, ja: "「生まれたての神霊」", en:'"Newborn Divine Spirits"'},
      {id: 106, ja: "「生まれたての神霊」", en:'"Newborn Divine Spirits"'},
      {id: 107, ja: "アンノウン「軌道不明の鬼火」", en:'Unknown "Will-o\'-wisps in Unknown Orbit"'},
      {id: 108, ja: "アンノウン「姿態不明の空魚」", en:'Unknown "Skyfish with Unknown Shape"'},
      {id: 109, ja: "アンノウン「原理不明の妖怪玉」", en:'Unknown "Youkai Orb of Unknown Mechanics"'},
      {id: 110, ja: "壱番勝負「霊長化弾幕変化」", en:'First Duel "Primate Danmaku Transformation"'},
      {id: 111, ja: "弐番勝負「肉食化弾幕変化」", en:'Second Duel "Carnivorous Danmaku Transformation"'},
      {id: 112, ja: "参番勝負「延羽化弾幕変化」", en:'Third Duel "Avian Danmaku Transformation"'},
      {id: 113, ja: "四番勝負「両生化弾幕変化」", en:'Fourth Duel "Amphibian Danmaku Transformation"'},
      {id: 114, ja: "伍番勝負「鳥獣戯画」", en:'Fifth Duel "Scrolls of Frolicking Animals"'},
      {id: 115, ja: "六番勝負「狸の化け学校」", en:'Sixth Duel "Tanuki\'s Monstrous School"'},
      {id: 116, ja: "七番勝負「野生の離島」", en:'Seventh Duel "Wild Deserted Island"'},
      {id: 117, ja: "変化「まぬけ巫女の偽調伏」", en:'Transformation "Pseudo-Exorcism of the Stupid Shrine Maiden"'},
      {id: 118, ja: "「マミゾウ化弾幕十変化」", en:'"Mamizou Danmaku in Ten Transformations"'},
      {id: 119, ja: "狢符「満月のポンポコリン」", en:'Raccoon Sign "Full Moon Pompokolin"'},
      {id: 120, ja: "桜符「桜吹雪地獄」", en:'Cherry Blossom Sign "Cherry Blossom Blizzard Hell"'},
      {id: 121, ja: "山彦「ヤマビコの本領発揮エコー」", en:'Mountain Echo "Yamabiko\'s Specialty Echo Demonstration"'},
      {id: 122, ja: "毒爪「死なない殺人鬼」", en:'Poison Nail "Undead Murderer"'},
      {id: 123, ja: "道符「ＴＡＯ胎動　〜道〜」", en:'Taoist Sign "TAO Fetal Movement ~Dao~"'},
      {id: 124, ja: "怨霊「入鹿の雷」", en:'Vengeful Spirit "Iruka\'s Thunder"'},
      {id: 125, ja: "聖童女「太陽神の贄」", en:'Saint Girl "Sun Goddess\'s Sacrifice"'},
      {id: 126, ja: "「神霊大宇宙」", en:'"Divine Spirits\' Universe"'},
      {id: 127, ja: "「ワイルドカーペット」", en:'"Wild Carpet"'},
    ]
  }
</script>