<script setup lang="ts">
  export function th17SpellCard(spellCardId: number){
    const spellCardMap=[
      {id: 1, ja: "石符「ストーンウッズ」", en: 'Stone Sign "Stone Woods"'},
      {id: 2, ja: "石符「ストーンウッズ」", en: 'Stone Sign "Stone Woods"'},
      {id: 3, ja: "石符「ストーンコニファー」", en: 'Stone Sign "Stone Conifers"'},
      {id: 4, ja: "石符「ストーンコニファー」", en: 'Stone Sign "Stone Conifers"'},
      {id: 5, ja: "石符「チルドレンズリンボ」", en: 'Stone Sign "Children\'s Limbo"'},
      {id: 6, ja: "石符「チルドレンズリンボ」", en: 'Stone Sign "Children\'s Limbo"'},
      {id: 7, ja: "石符「アダルトチルドレンズリンボ」", en: 'Stone Sign "Adult Children\'s Limbo"'},
      {id: 8, ja: "石符「アダルトチルドレンズリンボ」", en: 'Stone Sign "Adult Children\'s Limbo"'},
      {id: 9, ja: "石符「ストーンベイビー」", en: 'Stone Sign "Stone Baby"'},
      {id: 10, ja: "石符「ストーンベイビー」", en: 'Stone Sign "Stone Baby"'},
      {id: 11, ja: "石符「ヘビーストーンベイビー」", en: 'Stone Sign "Heavy Stone Baby"'},
      {id: 12, ja: "石符「ヘビーストーンベイビー」", en: 'Stone Sign "Heavy Stone Baby"'},
      {id: 13, ja: "溺符「三途の淪溺」", en: 'Drowning Sign "Drowning in the Sanzu"'},
      {id: 14, ja: "溺符「三途の淪溺」", en: 'Drowning Sign "Drowning in the Sanzu"'},
      {id: 15, ja: "溺符「三途の淪溺」", en: 'Drowning Sign "Drowning in the Sanzu"'},
      {id: 16, ja: "溺符「三途の淪溺」", en: 'Drowning Sign "Drowning in the Sanzu"'},
      {id: 17, ja: "鬼符「デーモンシージ」", en: 'Oni Sign "Demon Siege"'},
      {id: 18, ja: "鬼符「デーモンシージ」", en: 'Oni Sign "Demon Siege"'},
      {id: 19, ja: "鬼符「ハングリーデーモンシージ」", en: 'Oni Sign "Hungry Demon Siege"'},
      {id: 20, ja: "鬼符「ハングリーデーモンシージ」", en: 'Oni Sign "Hungry Demon Siege"'},
      {id: 21, ja: "水符「水配りの試練」", en: 'Water Sign "Ordeal of Water Distribution"'},
      {id: 22, ja: "水符「水配りの試練」", en: 'Water Sign "Ordeal of Water Distribution"'},
      {id: 23, ja: "水符「水配りの上級試煉」", en: 'Water Sign "High-Level Purgatordeal of Water Distribution"'},
      {id: 24, ja: "水符「水配りの極級試煉」", en: 'Water Sign "Ultimate Purgatordeal of Water Distribution"'},
      {id: 25, ja: "光符「見渡しの試練」", en: 'Light Sign "Ordeal of Surveying"'},
      {id: 26, ja: "光符「見渡しの試練」", en: 'Light Sign "Ordeal of Surveying"'},
      {id: 27, ja: "光符「見渡しの上級試煉」", en: 'Light Sign "High-Level Purgatordeal of Surveying"'},
      {id: 28, ja: "光符「見渡しの極級試煉」", en: 'Light Sign "Ultimate Purgatordeal of Surveying"'},
      {id: 29, ja: "鬼符「鬼渡の試練」", en: 'Oni Sign "Purgatordeal of Oniwatari"'},
      {id: 30, ja: "鬼符「鬼渡の試練」", en: 'Oni Sign "Purgatordeal of Oniwatari"'},
      {id: 31, ja: "鬼符「鬼渡の上級試煉」", en: 'Oni Sign "High-Level Purgatordeal of Oniwatari"'},
      {id: 32, ja: "鬼符「鬼渡の獄級試煉」", en: 'Oni Sign "Hell-Level Purgatordeal of Oniwatari"'},
      {id: 33, ja: "亀符「亀甲地獄」", en: 'Tortoise Sign "Tortoiseshell Hell"'},
      {id: 34, ja: "亀符「亀甲地獄」", en: 'Tortoise Sign "Tortoiseshell Hell"'},
      {id: 35, ja: "亀符「亀甲地獄」", en: 'Tortoise Sign "Tortoiseshell Hell"'},
      {id: 36, ja: "亀符「亀甲地獄」", en: 'Tortoise Sign "Tortoiseshell Hell"'},
      {id: 37, ja: "鬼符「搦手の畜生」", en: 'Oni Sign "Beasts Attacking from the Rear"'},
      {id: 38, ja: "鬼符「搦手の畜生」", en: 'Oni Sign "Beasts Attacking from the Rear"'},
      {id: 39, ja: "鬼符「搦手の犬畜生」", en: 'Oni Sign "Mangy Beasts Attacking from the Rear"'},
      {id: 40, ja: "鬼符「搦手の鬼畜生」", en: 'Oni Sign "Devilish Beasts Attacking from the Rear"'},
      {id: 41, ja: "龍符「龍紋弾」", en: 'Dragon Sign "Dragon Crest Bullets"'},
      {id: 42, ja: "龍符「龍紋弾」", en: 'Dragon Sign "Dragon Crest Bullets"'},
      {id: 43, ja: "龍符「龍紋弾」", en: 'Dragon Sign "Dragon Crest Bullets"'},
      {id: 44, ja: "龍符「龍紋弾」", en: 'Dragon Sign "Dragon Crest Bullets"'},
      {id: 45, ja: "埴輪「弓兵埴輪」", en: 'Haniwa "Archer Haniwa"'},
      {id: 46, ja: "埴輪「弓兵埴輪」", en: 'Haniwa "Archer Haniwa"'},
      {id: 47, ja: "埴輪「熟練弓兵埴輪」", en: 'Haniwa "Skilled Archer Haniwa"'},
      {id: 48, ja: "埴輪「熟練弓兵埴輪」", en: 'Haniwa "Skilled Archer Haniwa"'},
      {id: 49, ja: "埴輪「剣士埴輪」", en: 'Haniwa "Fencer Haniwa"'},
      {id: 50, ja: "埴輪「剣士埴輪」", en: 'Haniwa "Fencer Haniwa"'},
      {id: 51, ja: "埴輪「熟練剣士埴輪」", en: 'Haniwa "Skilled Fencer Haniwa"'},
      {id: 52, ja: "埴輪「熟練剣士埴輪」", en: 'Haniwa "Skilled Fencer Haniwa"'},
      {id: 53, ja: "埴輪「騎馬兵埴輪」", en: 'Haniwa "Cavalry Haniwa"'},
      {id: 54, ja: "埴輪「騎馬兵埴輪」", en: 'Haniwa "Cavalry Haniwa"'},
      {id: 55, ja: "埴輪「熟練騎馬兵埴輪」", en: 'Haniwa "Skilled Cavalry Haniwa"'},
      {id: 56, ja: "埴輪「熟練騎馬兵埴輪」", en: 'Haniwa "Skilled Cavalry Haniwa"'},
      {id: 57, ja: "埴輪「がらんどうの無尽兵団」", en: 'Haniwa "Hollow Inexhaustible Troops"'},
      {id: 58, ja: "埴輪「がらんどうの無尽兵団」", en: 'Haniwa "Hollow Inexhaustible Troops"'},
      {id: 59, ja: "埴輪「不敗の無尽兵団」", en: 'Haniwa "Undefeated Inexhaustible Troops"'},
      {id: 60, ja: "埴輪「不敗の無尽兵団」", en: 'Haniwa "Undefeated Inexhaustible Troops"'},
      {id: 61, ja: "方形「方形造形術」", en: 'Square Shape "Square-Shaped Sculpting Art"'},
      {id: 62, ja: "方形「方形造形術」", en: 'Square Shape "Square-Shaped Sculpting Art"'},
      {id: 63, ja: "方形「スクエアクリーチャー」", en: 'Square Shape "Square Creature"'},
      {id: 64, ja: "方形「スクエアクリーチャー」", en: 'Square Shape "Square Creature"'},
      {id: 65, ja: "円形「真円造形術」", en: 'Circular Shape "Perfect Circle Sculpting Art"'},
      {id: 66, ja: "円形「真円造形術」", en: 'Circular Shape "Perfect Circle Sculpting Art"'},
      {id: 67, ja: "円形「サークルクリーチャー」", en: 'Circular Shape "Circle Creature"'},
      {id: 68, ja: "円形「サークルクリーチャー」", en: 'Circular Shape "Circle Creature"'},
      {id: 69, ja: "線形「線形造形術」", en: 'Linear Shape "Line-Shaped Sculpting Art"'},
      {id: 70, ja: "線形「線形造形術」", en: 'Linear Shape "Line-Shaped Sculpting Art"'},
      {id: 71, ja: "線形「リニアクリーチャー」", en: 'Linear Shape "Linear Creature"'},
      {id: 72, ja: "線形「リニアクリーチャー」", en: 'Linear Shape "Linear Creature"'},
      {id: 73, ja: "埴輪「偶像人馬造形術」", en: 'Haniwa "Horse-and-Rider Idol Sculpting Art"'},
      {id: 74, ja: "埴輪「偶像人馬造形術」", en: 'Haniwa "Horse-and-Rider Idol Sculpting Art"'},
      {id: 75, ja: "埴輪「アイドルクリーチャー」", en: 'Haniwa "Idol Creature"'},
      {id: 76, ja: "埴輪「アイドルクリーチャー」", en: 'Haniwa "Idol Creature"'},
      {id: 77, ja: "「鬼形造形術」", en: '"Oni-Shaped Sculpting Art"'},
      {id: 78, ja: "「鬼形造形術」", en: '"Oni-Shaped Sculpting Art"'},
      {id: 79, ja: "「鬼形造形術」", en: '"Oni-Shaped Sculpting Art"'},
      {id: 80, ja: "「鬼形造形術」", en: '"Oni-Shaped Sculpting Art"'},
      {id: 81, ja: "「ジオメトリッククリーチャー」", en: '"Geometric Creature"'},
      {id: 82, ja: "「ジオメトリッククリーチャー」", en: '"Geometric Creature"'},
      {id: 83, ja: "「ジオメトリッククリーチャー」", en: '"Geometric Creature"'},
      {id: 84, ja: "「ジオメトリッククリーチャー」", en: '"Geometric Creature"'},
      {id: 85, ja: "「イドラディアボルス」", en: '"Idola Diabolus"'},
      {id: 86, ja: "「イドラディアボルス」", en: '"Idola Diabolus"'},
      {id: 87, ja: "「イドラディアボルス」", en: '"Idola Diabolus"'},
      {id: 88, ja: "「イドラディアボルス」", en: '"Idola Diabolus"'},
      {id: 89, ja: "血戦「血の分水嶺」", en: 'Bloody Battle "Watershed of Blood"'},
      {id: 90, ja: "血戦「獄界視線」", en: 'Bloody Battle "Hell Realm Sight-Line"'},
      {id: 91, ja: "血戦「全霊鬼渡り」", en: 'Bloody Battle "All-Spirit Oniwatari"'},
      {id: 92, ja: "勁疾技「スリリングショット」", en: 'Agile Skill "Thrilling Shot"'},
      {id: 93, ja: "勁疾技「ライトニングネイ」", en: 'Agile Skill "Lightning Neigh"'},
      {id: 94, ja: "勁疾技「デンスクラウド」", en: 'Agile Skill "Dense Crowd"'},
      {id: 95, ja: "勁疾技「ビーストエピデミシティ」", en: 'Agile Skill "Beast Epidemicity"'},
      {id: 96, ja: "勁疾技「トライアングルチェイス」", en: 'Agile Skill "Triangle Chase"'},
      {id: 97, ja: "勁疾技「ブラックペガサス流星弾」", en: 'Agile Skill "Black Pegasus Meteor Shot"'},
      {id: 98, ja: "勁疾技「マッスルエクスプロージョン」", en: 'Agile Skill "Muscle Explosion"'},
      {id: 99, ja: "「フォロミーアンアフライド」", en: '"Follow Me, Unafraid"'},
      {id: 100, ja: "「鬼形のホイポロイ」", en: '"Oni-Shaped Hoi Polloi"'},
      {id: 101, ja: "「鬼畜生の所業」", en: '"Deeds of Devilish Beasts"'},
    ]
  }
</script>