<script setup lang="ts">
  export function th18SpellCard(spellCardId: number){
    const spellCardMap=[
      {id: 1, ja: "招符「弾幕万来」", en: 'Beckon Sign "Danmaku Business Boom"'},
      {id: 2, ja: "招符「弾幕万来」", en: 'Beckon Sign "Danmaku Business Boom"'},
      {id: 3, ja: "招符「弾幕万来」", en: 'Beckon Sign "Danmaku Business Boom"'},
      {id: 4, ja: "招符「弾幕万来」", en: 'Beckon Sign "Danmaku Business Boom"'},
      {id: 5, ja: "招符「弾災招福」", en: 'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"'},
      {id: 6, ja: "招符「弾災招福」", en: 'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"'},
      {id: 7, ja: "招符「弾災招福」", en: 'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"'},
      {id: 8, ja: "招符「弾災招福」", en: 'Beckon Sign "Shoot Away Disaster, Beckon in Fortune"'},
      {id: 9, ja: "森符「木隠れの技術」", en: 'Forest Sign "Tree-Veiling Technology"'},
      {id: 10, ja: "森符「木隠れの技術」", en: 'Forest Sign "Tree-Veiling Technology"'},
      {id: 11, ja: "森符「極・木隠れの技術」", en: 'Forest Sign "Extreme Tree-Veiling Technology"'},
      {id: 12, ja: "森符「真・木隠れの技術」", en: 'Forest Sign "True Tree-Veiling Technology"'},
      {id: 13, ja: "森符「最奥の森域」", en: 'Forest Sign "Innermost Forest Region"'},
      {id: 14, ja: "森符「最奥の森域」", en: 'Forest Sign "Innermost Forest Region"'},
      {id: 15, ja: "森符「極・最奥の森域」", en: 'Forest Sign "Extreme Innermost Forest Region"'},
      {id: 16, ja: "森符「真・最奥の森域」", en: 'Forest Sign "True Innermost Forest Region"'},
      {id: 17, ja: "葉技「グリーンスパイラル」", en: 'Leaf Skill "Green Spiral"'},
      {id: 18, ja: "葉技「グリーンスパイラル」", en: 'Leaf Skill "Green Spiral"'},
      {id: 19, ja: "葉技「グリーンサイクロン」", en: 'Leaf Skill "Green Cyclone"'},
      {id: 20, ja: "葉技「グリーントルネード」", en: 'Leaf Skill "Green Tornado"'},
      {id: 21, ja: "山符「動天の雲間草」", en: 'Mountain Sign "Heaven-Shaking Kumomagusa"'},
      {id: 22, ja: "山符「動天の雲間草」", en: 'Mountain Sign "Heaven-Shaking Kumomagusa"'},
      {id: 23, ja: "山怪「驚愕の雲間草」", en: 'Mountain Apparition "Astonishing Kumomagusa"'},
      {id: 24, ja: "山怪「驚愕の雲間草」", en: 'Mountain Apparition "Astonishing Kumomagusa"'},
      {id: 25, ja: "山符「妖光輝く薄雪草」", en: 'Mountain Sign "Usuyukisou Shining with Bewitching Light"'},
      {id: 26, ja: "山符「妖光輝く薄雪草」", en: 'Mountain Sign "Usuyukisou Shining with Bewitching Light"'},
      {id: 27, ja: "山怪「妖魔犇めく薄雪草」", en: 'Mountain Apparition "Usuyukisou of Thronging Crowds of Youma"'},
      {id: 28, ja: "山怪「妖魔犇めく薄雪草」", en: 'Mountain Apparition "Usuyukisou of Thronging Crowds of Youma"'},
      {id: 29, ja: "山花「殺戮の駒草」", en: 'Mountain Flower "Komakusa of Massacre"'},
      {id: 30, ja: "山花「殺戮の駒草」", en: 'Mountain Flower "Komakusa of Massacre"'},
      {id: 31, ja: "山花「殺戮の山の女王」", en: 'Mountain Flower "Mountain Queen of Massacre"'},
      {id: 32, ja: "山花「殺戮の山の女王」", en: 'Mountain Flower "Mountain Queen of Massacre"'},
      {id: 33, ja: "玉符「虹龍陰陽玉」", en: 'Orb Sign "Rainbow Dragon Yin-Yang Orbs"'},
      {id: 34, ja: "玉符「虹龍陰陽玉」", en: 'Orb Sign "Rainbow Dragon Yin-Yang Orbs"'},
      {id: 35, ja: "玉符「虹龍陰陽玉」", en: 'Orb Sign "Rainbow Dragon Yin-Yang Orbs"'},
      {id: 36, ja: "玉符「陰陽神玉」", en: 'Orb Sign "Yin-Yang Divine Orbs"'},
      {id: 37, ja: "玉将「クイーンオブインヤンスフィア」", en: 'Jeweled General "Queen of Yin-Yang Sphere"'},
      {id: 38, ja: "玉将「クイーンオブインヤンスフィア」", en: 'Jeweled General "Queen of Yin-Yang Sphere"'},
      {id: 39, ja: "女王珠「虹の扉の向こうに」", en: 'Queenly Gem "Beyond the Rainbow Door"'},
      {id: 40, ja: "女王珠「虹の扉の向こうに」", en: 'Queenly Gem "Beyond the Rainbow Door"'},
      {id: 41, ja: "「陰陽サフォケイション」", en: '"Yin-Yang Suffocation"'},
      {id: 42, ja: "「陰陽サフォケイション」", en: '"Yin-Yang Suffocation"'},
      {id: 43, ja: "「陰陽サフォケイション」", en: '"Yin-Yang Suffocation"'},
      {id: 44, ja: "「陰陽サフォケイション」", en: '"Yin-Yang Suffocation"'},
      {id: 45, ja: "禍星「星火燎原の舞」", en: 'Calamitous Star "Dance of Star-Sparked Wildfire"'},
      {id: 46, ja: "禍星「星火燎原の舞」", en: 'Calamitous Star "Dance of Star-Sparked Wildfire"'},
      {id: 47, ja: "禍星「星火燎原乱舞」", en: 'Calamitous Star "Wild Dance of Star-Sparked Wildfire"'},
      {id: 48, ja: "禍星「星火燎原乱舞」", en: 'Calamitous Star "Wild Dance of Star-Sparked Wildfire"'},
      {id: 49, ja: "星風「虹彩陸離の舞」", en: 'Stellar Wind "Dance of Dazzling Iridescence"'},
      {id: 50, ja: "星風「虹彩陸離の舞」", en: 'Stellar Wind "Dance of Dazzling Iridescence"'},
      {id: 51, ja: "星風「虹彩陸離乱舞」", en: 'Stellar Wind "Wild Dance of Dazzling Iridescence"'},
      {id: 52, ja: "星風「虹彩陸離乱舞」", en: 'Stellar Wind "Wild Dance of Dazzling Iridescence"'},
      {id: 53, ja: "光馬「天馬行空の舞」", en: 'Luminous Horse "Dance of Sky-Racing Heavenly Steeds"'},
      {id: 54, ja: "光馬「天馬行空の舞」", en: 'Luminous Horse "Dance of Sky-Racing Heavenly Steeds"'},
      {id: 55, ja: "光馬「天馬行空乱舞」", en: 'Luminous Horse "Wild Dance of Sky-Racing Heavenly Steeds"'},
      {id: 56, ja: "光馬「天馬行空乱舞」", en: 'Luminous Horse "Wild Dance of Sky-Racing Heavenly Steeds"'},
      {id: 57, ja: "虹光「光風霽月」", en: 'Rainbow Illumination "Clear and Tranquil Wind and Moon"'},
      {id: 58, ja: "虹光「光風霽月」", en: 'Rainbow Illumination "Clear and Tranquil Wind and Moon"'},
      {id: 59, ja: "虹光「光風霽月」", en: 'Rainbow Illumination "Clear and Tranquil Wind and Moon"'},
      {id: 60, ja: "虹光「光風霽月」", en: 'Rainbow Illumination "Clear and Tranquil Wind and Moon"'},
      {id: 61, ja: "「無主への供物」", en: '"An Offering to the Ownerless"'},
      {id: 62, ja: "「無主への供物」", en: '"An Offering to the Ownerless"'},
      {id: 63, ja: "「無主への供物」", en: '"An Offering to the Ownerless"'},
      {id: 64, ja: "「無主への供物」", en: '"An Offering to the Ownerless"'},
      {id: 65, ja: "「弾幕狂蒐家の妄執」", en: '"Danmaku Hoarder\'s Obsession"'},
      {id: 66, ja: "「弾幕狂蒐家の妄執」", en: '"Danmaku Hoarder\'s Obsession"'},
      {id: 67, ja: "「弾幕狂蒐家の妄執」", en: '"Danmaku Hoarder\'s Obsession"'},
      {id: 68, ja: "「弾幕狂蒐家の妄執」", en: '"Danmaku Hoarder\'s Obsession"'},
      {id: 69, ja: "「バレットマーケット」", en: '"Bullet Market"'},
      {id: 70, ja: "「バレットマーケット」", en: '"Bullet Market"'},
      {id: 71, ja: "「密度の高いバレットマーケット」", en: '"High Density Bullet Market"'},
      {id: 72, ja: "「弾幕自由市場」", en: '"Danmaku Free Market"'},
      {id: 73, ja: "「虹人環」", en: '"Rainbow Ring of People"'},
      {id: 74, ja: "「虹人環」", en: '"Rainbow Ring of People"'},
      {id: 75, ja: "「虹人環」", en: '"Rainbow Ring of People"'},
      {id: 76, ja: "「虹人環」", en: '"Rainbow Ring of People"'},
      {id: 77, ja: "「バレットドミニオン」", en: '"Bullet Dominion"'},
      {id: 78, ja: "「バレットドミニオン」", en: '"Bullet Dominion"'},
      {id: 79, ja: "「暴虐のバレットドミニオン」", en: '"Tyrannical Bullet Dominion"'},
      {id: 80, ja: "「無道のバレットドミニオン」", en: '"Inhumane Bullet Dominion"'},
      {id: 81, ja: "「弾幕のアジール」", en: '"Asylum of Danmaku"'},
      {id: 82, ja: "「弾幕のアジール」", en: '"Asylum of Danmaku"'},
      {id: 83, ja: "「弾幕のアジール」", en: '"Asylum of Danmaku"'},
      {id: 84, ja: "「弾幕のアジール」", en: '"Asylum of Danmaku"'},
      {id: 85, ja: "狐符「フォックスワインダー」", en: 'Fox Sign "Fox Winder"'},
      {id: 86, ja: "管狐「シリンダーフォックス」", en: 'Kuda-gitsune "Cylinder Fox"'},
      {id: 87, ja: "星狐「天狐龍星の舞」", en: 'Stellar Fox "Dance of Heavenly Foxes and Dragon Stars"'},
      {id: 88, ja: "蠱毒「カニバリスティックインセクト」", en: 'Kodoku "Cannibalistic Insect"'},
      {id: 89, ja: "蠱毒「ケイブスウォーマー」", en: 'Kodoku "Cave Swarmer"'},
      {id: 90, ja: "蠱毒「スカイペンドラ」", en: 'Kodoku "Sky Pendra"'},
      {id: 91, ja: "採掘「積もり続けるマインダンプ」", en: 'Mining "Ever-Accumulating Mine Dump"'},
      {id: 92, ja: "採掘「マインブラスト」", en: 'Mining "Mine Blast"'},
      {id: 93, ja: "採掘「妖怪達のシールドメソッド」", en: 'Mining "Shield Method of the Youkai"'},
      {id: 94, ja: "大蜈蚣「スネークイーター」", en: 'Oomukade "Snake Eater"'},
      {id: 95, ja: "大蜈蚣「ドラゴンイーター」", en: 'Oomukade "Dragon Eater"'},
      {id: 96, ja: "「蠱毒のグルメ」", en: '"Kodoku Gourmet"'},
      {id: 97, ja: "「蟲姫さまの輝かしく落ち着かない毎日」", en: '"Mushihime-sama\'s Resplendent and Restless Daily Life"'},
    ]
  }
</script>