@startuml

skinparam defaultFontName "Noto Sans CJK JP"



entity "replays" {
  + replay_id : int
  --
  * user_name: string
  * delete_password: string
  * delete_date: timestamp
  * is_using_thprac
  * digest: string
}

note right of replays
    スコアやリプレイファイル名などは全ての東方リプレイファイルに存在している
    よって正規化の観点からして本来であればreplaysに入れるのが適切だと考えられる
    しかしこのデータは今後の作品で消える可能性も考えられる
    よってreplaysにはこのウェブアプリに責任があるデータのみを入れる

    ただしthpracの有無についてはthprac非対応の作品であっても
    falseになるだけであり全作品に対応できるのでここで指定する
end note

entity "al01" as Profile {
  + profile_id : int
  --
  * user_id : int
  * address : string
}

' 1対1の関係
replays ||--|| Profile
@enduml