@startuml

class ReplayDispatcher{
    マジックナンバーを見て各ゲーム固有のパーサに振り分け
}

note as N1
各ゲームに固有なクラスはバイナリ上のマジックナンバーを用いて命名する
例: t06rReplayInfo
end note

class BaseReplayInfo{
    +convert_to_json()
}

class tXXrReplayInfo{

}

class BaseReplayParser {
    +parse()
}

class tXXrReplayParser{
    +parse()
}

class BaseDatabasehandler{
    +insert()
    +delete()
    +select()    
}

class tXXrDatabaseHandler{
    +insert()
    +delete()
    +select()
}

ReplayDispatcher  --> BaseReplayParser
ReplayDispatcher  --> tXXrReplayParser
ReplayDispatcher  --> BaseReplayInfo
ReplayDispatcher  --> BaseDatabasehandler
ReplayDispatcher  --> tXXrDatabaseHandler

BaseReplayParser <|-- tXXrReplayParser
tXXrReplayParser  --> tXXrReplayInfo

BaseReplayInfo   <|-- tXXrReplayInfo

BaseDatabasehandler <|-- tXXrDatabaseHandler

@enduml